SELECT PARTICIP.GPGROUP, PARTICIP.GPPARTIC, PARTICIP.GPLAST, PARTICIP.GPFIRST, PARTICIP.GPMI, PARTICIP.GPSSN, PARTCOVG.PEFROMDT, PARTCOVG.PETODATE, PARTCOVG.PECOVCAT1, PARTCOVG.PECOVCAT2, 
PARTCOVG.PECOVCAT3, PARTCOVG.PECOVCAT4, PARTCOVG.PECOVCAT5, PARTCOVG.PECOVCAT6, PARTCOVG.PECOVCAT7, PARTCOVG.PECOVCAT8, PARTCOVG.PECOVCAT9, PARTCOVG.PECOVCAT10, PARTCOVG.PECOVCAT11, 
PARTCOVG.PECOVCAT12, PARTCOVG.PECOVCAT13, PARTCOVG.PEPLAN1, PARTCOVG.PEPLAN2, PARTCOVG.PEPLAN3, PARTCOVG.PEPLAN4, PARTCOVG.PEPLAN5, PARTCOVG.PEPLAN6, PARTCOVG.PEPLAN7, PARTCOVG.PEPLAN8, 
PARTCOVG.PEPLAN9, PARTCOVG.PEPLAN10, PARTCOVG.PEPLAN11, PARTCOVG.PEPLAN12, PARTCOVG.PEPLAN13, PARTCOVG.PEENRLEV1, PARTCOVG.PEENRLEV2, PARTCOVG.PEENRLEV3, PARTCOVG.PEENRLEV4, PARTCOVG.PEENRLEV5, 
PARTCOVG.PEENRLEV6, PARTCOVG.PEENRLEV7, PARTCOVG.PEENRLEV8, PARTCOVG.PEENRLEV9, PARTCOVG.PEENRLEV10, PARTCOVG.PEENRLEV11, PARTCOVG.PEENRLEV12, PARTCOVG.PEENRLEV13 
INTO MHPPartCov
FROM PARTICIP INNER JOIN PARTCOVG ON (PARTICIP.GPPARTIC = PARTCOVG.PEPARTIC) AND (PARTICIP.GPGROUP = PARTCOVG.PEGROUP)
WHERE (((PARTICIP.GPGROUP)=[Group ID]) AND ((PARTCOVG.PEGROUP)=[Group ID]))
ORDER BY PARTICIP.GPPARTIC, PARTCOVG.PEFROMDT DESC;
